name: LoveBot

on:
  workflow_dispatch:
  push:
    branches:
      - master
  schedule:
    - cron: "0 */5 * * *"

concurrency:
  group: lovebot
  cancel-in-progress: true

jobs:
  bot:
    runs-on: ubuntu-latest
    timeout-minutes: 290

    steps:
      - name: Download repository
        uses: actions/checkout@v6

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Start bot
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        run: python bot.py
